FROM php:7.4-fpm
COPY php.ini /usr/local/etc/php/

RUN apt-get update \ 
  && apt-get install -y libzip-dev \
  && docker-php-ext-install zip

#Composer install
# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
#   && php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
#   && php composer-setup.php \
#   && php -r "unlink('composer-setup.php');" \
#   && mv composer.phar /usr/local/bin/composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1

ENV COMPOSER_HOME /composer

ENV PATH $PATH:/composer/vendor/bin

WORKDIR /var/www/html

# RUN composer global require "laravel/installer"

# RUN apt-get update \
#   && apk --no-cache add \
#   postgresql-dev php-pgsql autoconf build-base
# RUN pecl install xdebug
# RUN docker-php-ext-install pdo_pgsql pgsql
# RUN docker-php-ext-enable xdebug

# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
