version: "3"
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ../laravel_vue_ts_seating_chart:/var/www/html/

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ../laravel_vue_ts_seating_chart:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  # mysql:
  #   image: mysql:5.7
  #   container_name: db-host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: database
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: "Asia/Tokyo"
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #     - ./docker/db/data:/var/lib/mysql
  #     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./docker/db/sql:/docker-entrypoint-initdb.d
  #   ports:
  #     - 3306:3306
